#!/bin/sh

#cleanup
rm -rf obj_dir
rm -rf counter.vcd

#run Verilator to translate Verilog into C++, including c++ testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run executable simulation file
obj_dir/Vsinegen

~/Documents/iac/lab0-devtools/tools/attach_usb.sh